/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import datos.archivo;
import datos.respuestas;
import tiquetes.RespuestaTiquete;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class tiquetesAdmin extends javax.swing.JFrame {
    
    private archivo datos = new archivo();
    private ArrayList<String[]> listaTiquetes = datos.leerArchivoCSV("tiquetes");
    private RespuestaTiquete utilidadTiquete = new RespuestaTiquete(listaTiquetes);
    private DefaultTableModel modelo = utilidadTiquete.getModelo();

    /**
     * Creates new form PreguntasAdmin
     */
    public tiquetesAdmin() {
        initComponents();
        setResizable(false);

        respuestasTable.setModel(modelo);
        respuestasTable.getColumnModel().getColumn(2).setPreferredWidth(300);
    }
    
    private void actulizar() {
        datos.crearArchivoCSV("tiquetes", listaTiquetes);
        utilidadTiquete = new RespuestaTiquete(listaTiquetes);
        modelo = utilidadTiquete.getModelo();
        respuestasTable.setModel(modelo);
        respuestasTable.getColumnModel().getColumn(2).setPreferredWidth(300);
        codigoTextField.setText("");
        casoTextArea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        respuestaIdLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        respuestaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        casoTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        respuestasTable = new javax.swing.JTable();
        listaRespuestasLabel = new javax.swing.JLabel();
        guardarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        activoRadioButton = new javax.swing.JRadioButton();
        ResueltoRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        respuestaIdLabel.setText("Codigo");

        respuestaLabel.setText("Caso:");

        casoTextArea.setColumns(20);
        casoTextArea.setRows(5);
        jScrollPane1.setViewportView(casoTextArea);

        respuestasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        respuestasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestasTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(respuestasTable);

        listaRespuestasLabel.setText("Lista de respuestas:");

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado:");

        buttonGroup1.add(activoRadioButton);
        activoRadioButton.setText("Activo");

        buttonGroup1.add(ResueltoRadioButton);
        ResueltoRadioButton.setText("Resuelto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activoRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(ResueltoRadioButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(respuestaIdLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                            .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(listaRespuestasLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(respuestaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuestaIdLabel)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarButton)
                    .addComponent(eliminarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuestaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activoRadioButton)
                    .addComponent(ResueltoRadioButton))
                .addGap(29, 29, 29)
                .addComponent(listaRespuestasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new chat().setVisible(true);
        this.setVisible(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//cancel
    }//GEN-LAST:event_formWindowClosing

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
         Date date =  new Date();
        String[] respuesta = datos.BuscarDato(codigoTextField.getText(), 0, listaTiquetes);
        
        if(respuesta != null) {
            for (int i = 0; i < listaTiquetes.size(); i++) {
                String[] linea = listaTiquetes.get(i);
                if(linea[0].replaceAll("\\s", "").equals(codigoTextField.getText().replaceAll("\\s", ""))) {
                    linea[2] = casoTextArea.getText().replaceAll(",", ".");
                }
            }
        } else {
            listaTiquetes.add(
                new String[] {
                    codigoTextField.getText().replaceAll("\\s", ""),
                    "IdUsuario",
                    casoTextArea.getText().replaceAll(",", "."),
                     "activo"
                }
            );
        }
        
        this.actulizar();
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void respuestasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestasTableMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = respuestasTable.getSelectedRow();
        
        if(filaSeleccionada!=-1){
            codigoTextField.setText(
                    respuestasTable.getValueAt(filaSeleccionada,0).toString()
            );
            casoTextArea.setText(
                    respuestasTable.getValueAt(filaSeleccionada,2).toString()
            );
            if(respuestasTable.getValueAt(filaSeleccionada,3).toString().equals("activo")) {
                activoRadioButton.setSelected(true);
            } else {
                ResueltoRadioButton.setSelected(true);
            }
        }
    }//GEN-LAST:event_respuestasTableMouseClicked

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        String[] respuesta = datos.BuscarDato(codigoTextField.getText(), 0, listaTiquetes);
        
        if(respuesta != null) {
            for (int i = 0; i < listaTiquetes.size(); i++) {
                String[] linea = listaTiquetes.get(i);
                if(linea[0].replaceAll("\\s", "").equals(codigoTextField.getText().replaceAll("\\s", ""))) {
                    listaTiquetes.remove(i);
                }
            }
        }
        this.actulizar();
    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiquetesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiquetesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiquetesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiquetesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiquetesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ResueltoRadioButton;
    private javax.swing.JRadioButton activoRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea casoTextArea;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listaRespuestasLabel;
    private javax.swing.JLabel respuestaIdLabel;
    private javax.swing.JLabel respuestaLabel;
    private javax.swing.JTable respuestasTable;
    // End of variables declaration//GEN-END:variables
}
